setup docker ci cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,4 +1,3 @@
-# CI/CD test
 name: Grade API CI/CD
 
 on:
@@ -13,7 +12,6 @@ on:
       - develop
 
 jobs:
-
   test:
     name: Test
     runs-on: ubuntu-latest
@@ -39,11 +37,9 @@ jobs:
 
       - name: Run unit and API tests
         run: npm test
-
   docker:
-    name: Build Docker Image
+    name: Build & Push Docker Image
     needs: test
-
     if: github.ref == 'refs/heads/main'
 
     runs-on: ubuntu-latest
@@ -51,18 +47,31 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v5
+      - name: Check Docker secrets
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          if [ -z "$DOCKER_USERNAME" ]; then
+            echo "DOCKER_USERNAME is missing"
+            exit 1
+          fi
 
+          if [ -z "$DOCKER_PASSWORD" ]; then
+            echo "DOCKER_PASSWORD is missing"
+            exit 1
+          fi
+
+          echo "Docker secrets are available"
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-
       - name: Build image
         run: |
           docker build \
             -t ${{ secrets.DOCKER_USERNAME }}/grade-api:latest .
-
       - name: Push image
         run: |
           docker push \
